
services:
  backend: 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3333:3333"
    depends_on:
      - postgres
  postgres:
    image: "bitnami/postgresql:latest"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanager
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: